services:
  minecraft-server:
    build: .
    environment:
      - SERVER_JAR=fabric-server.jar
    container_name: minecraft-server
    restart: unless-stopped
    volumes:
      - ./server:/minecraft/server
    ports:
      - "25565:25565"
    tty: true
    profiles:
      - server

  backup-service:
    image: busybox:latest
    container_name: minecraft-backup
    command: sh /backup.sh /minecraft/server/world /backup
    volumes:
      - ./backups:/backup
      - ./server:/minecraft/server
      - ./mcscripts/backup.sh:/backup.sh
    restart: "no"
    profiles:
      - backup
