services:
  minecraft-server:
    build: .
    container_name: minecraft-server
    # restart: unless-stopped
    volumes:
      - app-data:/minecraft/server
    ports:
      - "25565:25565"
    tty: true

volumes:
  app-data: