services:
  minecraft-server:
    build: .
    environment:
      - SERVER_JAR=fabric-server.jar
    container_name: minecraft-server
    restart: unless-stopped
    volumes:
      - minecraft-data:/minecraft/server
      - type: bind
        source: ./server
        target: /minecraft/server
    ports:
      - "25565:25565"
    tty: true

volumes:
  minecraft-data: