services:
  minecraft-server:
    build: .
    container_name: minecraft-server
    restart: unless-stopped
    volumes:
      - minecraft-data:/minecraft/server
      - type: bind
        source: ./world
        target: /minecraft/server/world
    ports:
      - "25565:25565"
    tty: true

volumes:
  minecraft-data: