services:
  minecraft-server:
    build: .
    environment:
      - SERVER_JAR=fabric-server.jar
    container_name: minecraft-server
    restart: unless-stopped
    volumes:
      - minecraft-data:/minecraft/server  # Mount Minecraft server data volume to persist server state
      - ./server:/minecraft/server        # Bind mount for server configuration and files
    ports:
      - "25565:25565"
    tty: true

  backup-service:
    image: busybox:latest
    container_name: minecraft-backup
    command: tar czf /backup/minecraft-$(date +%Y%m%d%H%M%S).tar.gz -C /data .
    volumes:
      - minecraft-data:/data:ro   # Read-only access to Minecraft data
      - ./backups:/backup         # Mount host backup directory
    entrypoint: []
    restart: "no"
    profiles:
      - backup

volumes:
  minecraft-data: